name: Crear Issue desde formulario

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
      email:
        required: true
      message:
        required: true

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Crear Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.FORM_SECRET }}
          script: |
            const name = inputs.name;
            const email = inputs.email;
            const message = inputs.message;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Nuevo mensaje de ${name}`,
              body: `**Nombre:** ${name}\n**Email:** ${email}\n\n**Mensaje:**\n${message}`
            });
