name: Formulario de contacto
description: Mensaje enviado desde la web
title: "Nuevo mensaje"
labels: ["formulario"]
body:
  - type: input
    id: nombre
    attributes:
      label: Nombre
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Email
    validations:
      required: true

  - type: textarea
    id: mensaje
    attributes:
      label: Mensaje
    validations:
      required: true
